#!/bin/bash -e

CURRENT_HTACCESS="/var/www/mysite/www/.htaccess"
ORIGINAL_HTACCESS="/var/www/mysite/www/.htaccess_original"
MAINTENANCE_HTML_PATH="/var/www/mysite/www/maintenance.html"

# move the original htaccess back into place
mv $ORIGINAL_HTACCESS $CURRENT_HTACCESS
rm $MAINTENANCE_HTML_PATH
