#!/bin/bash -e

SNAPSHOT_DIR="/var/www/mysite/snapshots"
TIMESTAMP=`date +"%Y-%d-%m_%H-%M-%S"`
LOCAL_SSPAK=${SNAPSHOT_DIR}/${TIMESTAMP}.sspak
REMOTE_SSPAK="s3://${bucket}/${key_name}"

if [ -z "$mode" ]; then
        mode="all"
fi

if [ -z "$webroot" ]; then
        echo "\$webroot not defined"
        exit 2
fi

rm -rf ${SNAPSHOT_DIR}
mkdir -p $SNAPSHOT_DIR

echo "Fetching snapshot"
/usr/local/bin/aws s3 --only-show-errors cp ${REMOTE_SSPAK} ${LOCAL_SSPAK}

echo "Running sspak load with mode '${mode}'"
/usr/local/bin/sspak load ${LOCAL_SSPAK} "${webroot}" --drop-db --${mode}

echo "Cleaning up"
rm -rf ${SNAPSHOT_DIR}