#!/bin/bash -e
if [ -z "$mode" ]; then
	mode="all"
fi

if [ -z "$webroot" ]; then
	echo "\$webroot not defined"
	exit 2
fi

rm -rf /tmp/temp.pak
echo "Fetching snapshot"
/usr/local/bin/aws s3 --only-show-errors cp "s3://${bucket}/${key_name}" /tmp/temp.pak

echo "Running sspak load with mode '${mode}'"
/usr/local/bin/sspak load /tmp/temp.pak "${webroot}" --drop-db --${mode}

echo "Cleaning up"
rm -rf /tmp/temp.pak
