#!/usr/bin/env bash -e

if [ -z "$mode" ]; then
	mode="all"
fi

rm -rf /tmp/temp.pak

echo "Fetching snapshot"
curl --silent --output /tmp/temp.pak ${sspak_url}

echo "Running sspak load with mode '${mode}'"
sspak load /tmp/temp.pak "${webroot}" --${mode}

echo "Cleaning up"
rm -rf /tmp/temp.pak
