#!/bin/bash -e

if [ -z "$mode" ]; then
	mode="all"
fi

DATETIME=`date +"%Y-%d-%d_%H-%M-%S"`

rm -rf /tmp/temp.pak
echo "Running sspak save with mode '${mode}'"
sspak save $webroot /tmp/temp.pak --${mode}

echo "Saving snapshot"
aws s3 --only-show-errors cp /tmp/temp.pak "s3://${bucket}/${bucket_folder}/${DATETIME}.pak"

echo "Cleaning up"
rm -rf /tmp/temp.pak
echo "sspak_url=s3://${bucket}/${bucket_folder}/${DATETIME}.pak"